# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/grandprimeve3g/setup-makefiles.sh

PROPRIETARY_FILES := \
    bin/refnotify \
    bin/engpc \
    lib/hw/gps.default.so \
    lib/libboost.so \
    lib/egl/libGLES_mali.so \
    etc/audio_hw.xml \
    etc/audio_para \
    etc/codec_pga.xml \
    etc/tiny_hw.xml \
    lib/libatchannel.so \
    bin/rild_sp \
    bin/modemd \
    bin/phoneserver \
    bin/modem_control \
    bin/ext_data.sh \
    bin/ext_kill.sh \
    bin/prepare_param.sh \
    lib/libril.so \
    lib/libmorpho_easy_hdr.so \
    lib/libAF.so \
	lib/libae.so \
    lib/libawb.so \
    lib/libmemoryheapion.so \
    lib/libomx_avcdec_hw_sprd.so \
    lib/libomx_avcenc_hw_sprd.so \
    lib/libomx_vpxdec_hw_sprd.so \
    lib/libomx_m4vh263dec_hw_sprd.so \
    lib/libomx_m4vh263enc_hw_sprd.so \
    lib/libstagefrighthw.so \
    lib/libstagefright_sprd_h264dec.so \
    lib/libstagefright_sprd_h264enc.so \
    lib/libstagefright_sprd_mpeg4dec.so \
    lib/libstagefright_sprd_mpeg4enc.so \
    lib/libstagefright_sprd_vpxdec.so \
    lib/hw/camera.sc8830.so \
    lib/hw/gralloc.sc8830.so \
    lib/hw/hwcomposer.sc8830.so \
    lib/hw/sensors.sc8830.so \
    lib/modules/mali.ko \
    lib/modules/sprdwl.ko \
    lib/hw/sprd_gsp.sc8830.so

PRODUCT_COPY_FILES += \
    $(foreach f,$(PROPRIETARY_FILES),vendor/lenovo/a1000/proprietary/$(f):system/$(f))
